# To merge datasets on atmosphere

- author : Sylvie Dagoret-Campagne
- date   : April 26th 2018
- affiliation : LAL/IN2P3/CNRS
- update : November 2018

- used in April 2018 for CTIO
- used in November 2018 for StarDice

In [36]:
import os,sys
import pandas as pd
import numpy as np

In [37]:
#path='datasets_2017'
path='datasets_2018'

In [38]:
#files=['MERRA2_2017_inst1_2d_asm_Nx_M2I1NXASM_ctio_AllYear.csv',
#       'MERRA2_2017_tavg1_2d_aer_Nx_M2T1NXAER_ctio_AllYear.csv',
#       'MERRA2_2017_tavg1_2d_rad_Nx_M2T1NXRAD_ctio_AllYear.csv']
files=['MERRA2_2018_inst1_2d_asm_Nx_M2I1NXASM_ohp_AllYear.csv',
       'MERRA2_2018_tavg1_2d_aer_Nx_M2T1NXAER_ohp_AllYear.csv',
       'MERRA2_2018_tavg1_2d_rad_Nx_M2T1NXRAD_ohp_AllYear.csv']

In [39]:
#output_file='MERRA2_2017_M2I1NXASM_M2T1NXAER_M2T1NXRAD_ctio_AllYear.csv'
output_file='MERRA2_2018_M2I1NXASM_M2T1NXAER_M2T1NXRAD_ohp_AllYear.csv'

# Read independant dataset

In [40]:
df1=pd.read_csv(os.path.join(path,files[0]))
df2=pd.read_csv(os.path.join(path,files[1]))
df3=pd.read_csv(os.path.join(path,files[2]))

# Specify which column is the index

- the index is the time

In [41]:
df1.set_index("time",inplace=True)
df1.head()

,PS,T10M,T2M,TO3,TOX,TQI,TQL,TQV,TS,U10M,U2M,U50M,V10M,V2M,V50M
time,,,,,,,,,,,,,,,
2018-01-01 00:00:00,93586.18,279.04254,277.92426,306.89130,0.006579,0.002162,0.319946,16.039366,277.08945,1.527891,0.762904,2.875433,-1.997757,-0.959274,-3.679868
2018-01-01 01:00:00,93644.22,278.96510,278.59644,308.94720,0.006623,0.002974,0.182983,15.441454,277.91504,4.309712,2.856233,6.262999,-4.501500,-2.982562,-6.735511
2018-01-01 02:00:00,93752.14,277.81226,277.56120,311.97500,0.006688,0.018402,0.112579,13.318526,276.94556,4.463664,3.018662,5.803768,-6.118572,-4.138448,-8.414824
2018-01-01 03:00:00,93814.81,277.13940,276.85822,315.93567,0.006773,0.024605,0.066193,11.264016,276.24167,3.333664,2.247162,4.378160,-6.393670,-4.307884,-8.974257
2018-01-01 04:00:00,93837.58,276.81490,276.42267,322.49008,0.006913,0.004604,0.045456,9.346043,275.63232,2.848288,1.887254,3.963684,-5.576814,-3.692428,-8.323152

In [42]:
df2.set_index("time",inplace=True)
df2.head()

                     TOTANGSTR  TOTEXTTAU  TOTSCATAU
time
2018-01-01 00:30:00   1.205785   0.139384   0.133389
2018-01-01 01:30:00   1.031252   0.114049   0.109637
2018-01-01 02:30:00   0.825740   0.066395   0.063274
2018-01-01 03:30:00   0.762376   0.051468   0.048648
2018-01-01 04:30:00   0.734917   0.046664   0.043992

In [43]:
df3.set_index("time",inplace=True)
df3.head()

                       TAUHGH      TAULOW     TAUMID    TAUTOT
time
2018-01-01 00:30:00  0.063202   61.296875   2.524414   63.8750
2018-01-01 01:30:00  0.000000   26.382812  13.625000   40.0000
2018-01-01 02:30:00  0.000000   20.085938  14.785156   34.8750
2018-01-01 03:30:00  0.000000   90.656250   4.283203   94.9375
2018-01-01 04:30:00  0.000000  173.062500   0.471924  173.5625

# concatenate in vertical the 2 first dataset and reorder by index

In [44]:
#df12=pd.concat([df1,df2]).sort_index()
#df12

In [45]:
df23=pd.concat([df2,df3],axis=1).sort_index()

In [46]:
df23.head()

,TOTANGSTR,TOTEXTTAU,TOTSCATAU,TAUHGH,TAULOW,TAUMID,TAUTOT
time,,,,,,,
2018-01-01 00:30:00,1.205785,0.139384,0.133389,0.063202,61.296875,2.524414,63.8750
2018-01-01 01:30:00,1.031252,0.114049,0.109637,0.000000,26.382812,13.625000,40.0000
2018-01-01 02:30:00,0.825740,0.066395,0.063274,0.000000,20.085938,14.785156,34.8750
2018-01-01 03:30:00,0.762376,0.051468,0.048648,0.000000,90.656250,4.283203,94.9375
2018-01-01 04:30:00,0.734917,0.046664,0.043992,0.000000,173.062500,0.471924,173.5625

In [47]:
df123=pd.concat([df1,df23],axis=0).sort_index()

/Users/dagoret/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [48]:
df123

,PS,T10M,T2M,TAUHGH,TAULOW,TAUMID,TAUTOT,TO3,TOTANGSTR,TOTEXTTAU,...,TQI,TQL,TQV,TS,U10M,U2M,U50M,V10M,V2M,V50M
time,,,,,,,,,,,,,,,,,,,,,
2018-01-01 00:00:00,93586.180,279.04254,277.92426,NaN,NaN,NaN,NaN,306.89130,NaN,NaN,...,0.002162,0.319946,16.039366,277.08945,1.527891,0.762904,2.875433,-1.997757,-0.959274,-3.679868
2018-01-01 00:30:00,NaN,NaN,NaN,0.063202,61.296875,2.524414,63.875000,NaN,1.205785,0.139384,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 01:00:00,93644.220,278.96510,278.59644,NaN,NaN,NaN,NaN,308.94720,NaN,NaN,...,0.002974,0.182983,15.441454,277.91504,4.309712,2.856233,6.262999,-4.501500,-2.982562,-6.735511
2018-01-01 01:30:00,NaN,NaN,NaN,0.000000,26.382812,13.625000,40.000000,NaN,1.031252,0.114049,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 02:00:00,93752.140,277.81226,277.56120,NaN,NaN,NaN,NaN,311.97500,NaN,NaN,...,0.018402,0.112579,13.318526,276.94556,4.463664,3.018662,5.803768,-6.118572,-4.138448,-8.414824
2018-01-01 02:30:00,NaN,NaN,NaN,0.000000,20.085938,14.785156,34.875000,NaN,0.825740,0.066395,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 03:00:00,93814.810,277.13940,276.85822,NaN,NaN,NaN,NaN,315.93567,NaN,NaN,...,0.024605,0.066193,11.264016,276.24167,3.333664,2.247162,4.378160,-6.393670,-4.307884,-8.974257
2018-01-01 03:30:00,NaN,NaN,NaN,0.000000,90.656250,4.283203,94.937500,NaN,0.762376,0.051468,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 04:00:00,93837.580,276.81490,276.42267,NaN,NaN,NaN,NaN,322.49008,NaN,NaN,...,0.004604,0.045456,9.346043,275.63232,2.848288,1.887254,3.963684,-5.576814,-3.692428,-8.323152
2018-01-01 04:30:00,NaN,NaN,NaN,0.000000,173.062500,0.471924,173.562500,NaN,0.734917,0.046664,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 05:00:00,93866.420,276.02676,275.49280,NaN,NaN,NaN,NaN,327.53333,NaN,NaN,...,0.000232,0.073364,8.057005,274.52893,2.951245,1.895436,4.603602,-4.405570,-2.826255,-7.216317
2018-01-01 05:30:00,NaN,NaN,NaN,0.000000,165.812500,0.188477,166.000000,NaN,0.688781,0.044910,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 06:00:00,93922.500,275.24063,274.55615,NaN,NaN,NaN,NaN,331.24805,NaN,NaN,...,0.000244,0.079498,7.431995,273.42260,2.955498,1.842217,5.069325,-3.931309,-2.439958,-7.102588
2018-01-01 06:30:00,NaN,NaN,NaN,0.000000,165.687500,0.177795,165.875000,NaN,0.676890,0.042335,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 07:00:00,93975.055,274.70984,273.92303,NaN,NaN,NaN,NaN,334.64633,NaN,NaN,...,0.000145,0.068756,7.019148,272.67813,2.743097,1.651798,4.934481,-3.494604,-2.087330,-6.591598
2018-01-01 07:30:00,NaN,NaN,NaN,0.000000,188.187500,0.000000,188.187500,NaN,0.704760,0.039589,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 08:00:00,93991.930,275.08762,274.41690,NaN,NaN,NaN,NaN,332.97556,NaN,NaN,...,0.000108,0.047272,6.777950,273.92242,2.533137,1.503361,4.449099,-2.930349,-1.723049,-5.417297
2018-01-01 08:30:00,NaN,NaN,NaN,0.000000,176.750000,0.050491,176.750000,NaN,0.707022,0.037503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 09:00:00,94039.860,276.93823,276.90625,NaN,NaN,NaN,NaN,332.02274,NaN,NaN,...,0.000078,0.034119,6.968413,277.09450,3.733483,2.555601,4.451899,-2.999113,-2.052722,-3.754127
2018-01-01 09:30:00,NaN,NaN,NaN,0.000000,103.531250,0.210999,103.718750,NaN,0.732250,0.036409,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 10:00:00,94107.960,278.26132,278.40967,NaN,NaN,NaN,NaN,332.82916,NaN,NaN,...,0.000755,0.030251,7.186449,279.02792,4.498859,3.138934,5.466366,-3.801327,-2.652566,-5.090155
2018-01-01 10:30:00,NaN,NaN,NaN,0.000283,86.812500,0.454468,87.281250,NaN,0.797715,0.035277,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 11:00:00,94074.160,279.23560,279.50568,NaN,NaN,NaN,NaN,334.69583,NaN,NaN,...,0.001880,0.038727,8.139877,280.40600,4.818671,3.378959,5.852292,-4.604501,-3.225776,-5.908912
2018-01-01 11:30:00,NaN,NaN,NaN,0.000000,50.468750,2.805664,53.265625,NaN,0.786483,0.038285,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 12:00:00,94010.625,279.81064,280.15094,NaN,NaN,NaN,NaN,337.60193,NaN,NaN,...,0.003145,0.050568,9.386897,281.22473,4.865758,3.435170,5.889538,-3.832758,-2.702192,-4.818791
2018-01-01 12:30:00,NaN,NaN,NaN,0.000000,24.085940,5.843750,29.929688,NaN,0.819494,0.039129,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 13:00:00,93883.740,280.01746,280.29434,NaN,NaN,NaN,NaN,337.98343,NaN,NaN,...,0.001748,0.059097,9.856486,281.22546,4.142404,2.944570,4.999680,-2.439124,-1.728653,-3.003480
2018-01-01 13:30:00,NaN,NaN,NaN,0.005400,36.046875,4.724609,40.781250,NaN,0.798818,0.040016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 14:00:00,93778.914,280.00122,280.11896,NaN,NaN,NaN,NaN,335.81815,NaN,NaN,...,0.000366,0.047592,9.833190,280.50370,4.119667,2.903456,5.042410,-0.575298,-0.401014,-0.739697
2018-01-01 14:30:00,NaN,NaN,NaN,0.187012,36.546875,0.137329,36.875000,NaN,0.662142,0.056065,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-10-31 09:00:00,93471.440,283.55258,283.31210,NaN,NaN,NaN,NaN,296.98810,NaN,NaN,...,0.073456,0.371338,18.530264,282.93774,-6.568367,-4.420412,-8.896851,5.775325,3.885477,8.061204
2018-10-31 09:30:00,NaN,NaN,NaN,3.802734,41.609375,19.968750,65.375000,NaN,0.952575,0.123468,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 10:00:00,93491.766,283.46370,283.27140,NaN,NaN,NaN,NaN,297.25308,NaN,NaN,...,0.094574,0.324219,18.351238,282.95178,-6.898643,-4.657596,-9.242619,5.855590,3.952348,8.006100
2018-10-31 10:30:00,NaN,NaN,NaN,2.190430,28.234377,26.898438,57.328125,NaN,0.929267,0.134281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 11:00:00,93512.210,283.29742,283.15167,NaN,NaN,NaN,NaN,299.39465,NaN,NaN,...,0.089081,0.292236,17.969673,282.87470,-7.573869,-5.128445,-10.110543,6.028186,4.082101,8.075232
2018-10-31 11:30:00,NaN,NaN,NaN,1.043457,21.710938,24.054688,46.812500,NaN,0.899668,0.129677,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 12:00:00,93494.805,283.12750,283.00037,NaN,NaN,NaN,NaN,301.58096,NaN,NaN,...,0.075684,0.235413,17.657770,282.78580,-7.973439,-5.407515,-10.466970,5.645320,3.830211,7.458768
2018-10-31 12:30:00,NaN,NaN,NaN,0.534668,24.757812,22.882812,48.171875,NaN,0.647865,0.180483,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 13:00:00,93462.090,283.25052,283.10870,NaN,NaN,NaN,NaN,303.35437,NaN,NaN,...,0.042297,0.203491,17.604265,282.83710,-7.932764,-5.376111,-10.498272,5.203524,3.528132,6.940145
2018-10-31 13:30:00,NaN,NaN,NaN,0.861572,26.757812,28.656250,56.265625,NaN,0.673147,0.182899,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 14:00:00,93450.060,283.58356,283.46002,NaN,NaN,NaN,NaN,304.45038,NaN,NaN,...,0.036148,0.182007,17.667171,283.23727,-7.717210,-5.233655,-9.987722,4.856726,3.293096,6.441003
2018-10-31 14:30:00,NaN,NaN,NaN,2.434570,26.132812,16.476562,45.046875,NaN,0.715448,0.175991,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 15:00:00,93435.250,283.28372,283.09910,NaN,NaN,NaN,NaN,304.60663,NaN,NaN,...,0.086121,0.222900,18.025175,282.69904,-7.261416,-4.903565,-9.559340,4.406269,2.977141,5.989860
2018-10-31 15:30:00,NaN,NaN,NaN,3.906250,21.375002,24.664062,49.937500,NaN,0.758167,0.204326,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 16:00:00,93441.250,282.74554,282.48200,NaN,NaN,NaN,NaN,305.42640,NaN,NaN,...,0.140564,0.246765,18.430946,281.92435,-6.698482,-4.493720,-9.146430,4.153125,2.786675,5.809068
2018-10-31 16:30:00,NaN,NaN,NaN,5.792969,22.843750,25.367188,54.000000,NaN,0.726027,0.221078,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 17:00:00,93458.950,282.57407,282.29180,NaN,NaN,NaN,NaN,305.68924,NaN,NaN,...,0.164185,0.256470,18.461630,281.75003,-6.691294,-4.483383,-9.164551,4.210543,2.822180,5.938331
2018-10-31 17:30:00,NaN,NaN,NaN,7.113281,27.765625,25.445312,60.328125,NaN,0.637565,0.205341,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 18:00:00,93475.760,282.61716,282.34418,NaN,NaN,NaN,NaN,304.50284,NaN,NaN,...,0.167908,0.253784,18.241314,281.81046,-6.813591,-4.566843,-9.373968,4.082680,2.737468,5.822247
2018-10-31 18:30:00,NaN,NaN,NaN,7.097656,27.148438,24.875000,59.125000,NaN,0.610869,0.221908,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 19:00:00,93487.560,282.67822,282.39886,NaN,NaN,NaN,NaN,303.52985,NaN,NaN,...,0.158936,0.229858,17.865297,281.84512,-6.996125,-4.689006,-9.632753,3.973953,2.664933,5.723583
2018-10-31 19:30:00,NaN,NaN,NaN,6.302734,35.968750,24.617188,66.875000,NaN,0.509567,0.209774,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 20:00:00,93490.055,282.66600,282.34265,NaN,NaN,NaN,NaN,303.37460,NaN,NaN,...,0.145874,0.223083,17.583904,281.70398,-7.420651,-4.971980,-10.246991,3.868461,2.592688,5.600542
2018-10-31 20:30:00,NaN,NaN,NaN,5.271484,22.531250,28.531250,56.343750,NaN,0.410124,0.225049,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 21:00:00,93495.180,282.49307,282.14453,NaN,NaN,NaN,NaN,304.21630,NaN,NaN,...,0.154114,0.225403,17.786602,281.44476,-7.423286,-4.965541,-10.314739,3.776929,2.527177,5.509329
2018-10-31 21:30:00,NaN,NaN,NaN,5.472656,15.753906,31.289062,52.515625,NaN,0.415198,0.279001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 22:00:00,93490.430,282.47490,282.14136,NaN,NaN,NaN,NaN,305.69480,NaN,NaN,...,0.160583,0.272583,18.129929,281.49194,-7.083616,-4.737393,-9.820744,3.942868,2.636917,5.764067
2018-10-31 22:30:00,NaN,NaN,NaN,5.751953,21.203125,31.187500,58.140625,NaN,0.404511,0.293909,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 23:00:00,93461.890,282.56350,282.27588,NaN,NaN,NaN,NaN,307.04504,NaN,NaN,...,0.165039,0.316162,18.254297,281.72880,-6.476371,-4.335044,-8.920647,4.112747,2.752313,6.001339
2018-10-31 23:30:00,NaN,NaN,NaN,5.417969,27.156250,29.968750,62.531250,NaN,0.370735,0.271580,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
#df123=pd.concat([df12,df3]).sort_index()

In [50]:
#df=df123.reindex_axis(['ps','pwv','ozone',
#                    'TOTEXTTAU','TOTANGSTR','TOTSCATAU',
#                    'TAUTOT','TAUHGH','TAUMID','TAULOW'], axis=1)
df=df123.reindex(['PS','TQV','TO3',
                  'TOTEXTTAU','TOTANGSTR','TOTSCATAU',
                  'TAUTOT','TAUHGH','TAUMID','TAULOW'], axis=1)
df

,PS,TQV,TO3,TOTEXTTAU,TOTANGSTR,TOTSCATAU,TAUTOT,TAUHGH,TAUMID,TAULOW
time,,,,,,,,,,
2018-01-01 00:00:00,93586.180,16.039366,306.89130,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 00:30:00,NaN,NaN,NaN,0.139384,1.205785,0.133389,63.875000,0.063202,2.524414,61.296875
2018-01-01 01:00:00,93644.220,15.441454,308.94720,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 01:30:00,NaN,NaN,NaN,0.114049,1.031252,0.109637,40.000000,0.000000,13.625000,26.382812
2018-01-01 02:00:00,93752.140,13.318526,311.97500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 02:30:00,NaN,NaN,NaN,0.066395,0.825740,0.063274,34.875000,0.000000,14.785156,20.085938
2018-01-01 03:00:00,93814.810,11.264016,315.93567,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 03:30:00,NaN,NaN,NaN,0.051468,0.762376,0.048648,94.937500,0.000000,4.283203,90.656250
2018-01-01 04:00:00,93837.580,9.346043,322.49008,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 04:30:00,NaN,NaN,NaN,0.046664,0.734917,0.043992,173.562500,0.000000,0.471924,173.062500
2018-01-01 05:00:00,93866.420,8.057005,327.53333,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 05:30:00,NaN,NaN,NaN,0.044910,0.688781,0.042307,166.000000,0.000000,0.188477,165.812500
2018-01-01 06:00:00,93922.500,7.431995,331.24805,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 06:30:00,NaN,NaN,NaN,0.042335,0.676890,0.039771,165.875000,0.000000,0.177795,165.687500
2018-01-01 07:00:00,93975.055,7.019148,334.64633,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 07:30:00,NaN,NaN,NaN,0.039589,0.704760,0.037041,188.187500,0.000000,0.000000,188.187500
2018-01-01 08:00:00,93991.930,6.777950,332.97556,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 08:30:00,NaN,NaN,NaN,0.037503,0.707022,0.035089,176.750000,0.000000,0.050491,176.750000
2018-01-01 09:00:00,94039.860,6.968413,332.02274,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 09:30:00,NaN,NaN,NaN,0.036409,0.732250,0.034083,103.718750,0.000000,0.210999,103.531250
2018-01-01 10:00:00,94107.960,7.186449,332.82916,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 10:30:00,NaN,NaN,NaN,0.035277,0.797715,0.032979,87.281250,0.000283,0.454468,86.812500
2018-01-01 11:00:00,94074.160,8.139877,334.69583,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 11:30:00,NaN,NaN,NaN,0.038285,0.786483,0.035976,53.265625,0.000000,2.805664,50.468750
2018-01-01 12:00:00,94010.625,9.386897,337.60193,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 12:30:00,NaN,NaN,NaN,0.039129,0.819494,0.036681,29.929688,0.000000,5.843750,24.085940
2018-01-01 13:00:00,93883.740,9.856486,337.98343,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 13:30:00,NaN,NaN,NaN,0.040016,0.798818,0.037434,40.781250,0.005400,4.724609,36.046875
2018-01-01 14:00:00,93778.914,9.833190,335.81815,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-01 14:30:00,NaN,NaN,NaN,0.056065,0.662142,0.053196,36.875000,0.187012,0.137329,36.546875
...,...,...,...,...,...,...,...,...,...,...
2018-10-31 09:00:00,93471.440,18.530264,296.98810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 09:30:00,NaN,NaN,NaN,0.123468,0.952575,0.118726,65.375000,3.802734,19.968750,41.609375
2018-10-31 10:00:00,93491.766,18.351238,297.25308,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 10:30:00,NaN,NaN,NaN,0.134281,0.929267,0.129306,57.328125,2.190430,26.898438,28.234377
2018-10-31 11:00:00,93512.210,17.969673,299.39465,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 11:30:00,NaN,NaN,NaN,0.129677,0.899668,0.124504,46.812500,1.043457,24.054688,21.710938
2018-10-31 12:00:00,93494.805,17.657770,301.58096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 12:30:00,NaN,NaN,NaN,0.180483,0.647865,0.172958,48.171875,0.534668,22.882812,24.757812
2018-10-31 13:00:00,93462.090,17.604265,303.35437,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 13:30:00,NaN,NaN,NaN,0.182899,0.673147,0.174952,56.265625,0.861572,28.656250,26.757812
2018-10-31 14:00:00,93450.060,17.667171,304.45038,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 14:30:00,NaN,NaN,NaN,0.175991,0.715448,0.168592,45.046875,2.434570,16.476562,26.132812
2018-10-31 15:00:00,93435.250,18.025175,304.60663,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 15:30:00,NaN,NaN,NaN,0.204326,0.758167,0.197047,49.937500,3.906250,24.664062,21.375002
2018-10-31 16:00:00,93441.250,18.430946,305.42640,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 16:30:00,NaN,NaN,NaN,0.221078,0.726027,0.213485,54.000000,5.792969,25.367188,22.843750
2018-10-31 17:00:00,93458.950,18.461630,305.68924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 17:30:00,NaN,NaN,NaN,0.205341,0.637565,0.197226,60.328125,7.113281,25.445312,27.765625
2018-10-31 18:00:00,93475.760,18.241314,304.50284,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 18:30:00,NaN,NaN,NaN,0.221908,0.610869,0.212989,59.125000,7.097656,24.875000,27.148438
2018-10-31 19:00:00,93487.560,17.865297,303.52985,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 19:30:00,NaN,NaN,NaN,0.209774,0.509567,0.199570,66.875000,6.302734,24.617188,35.968750
2018-10-31 20:00:00,93490.055,17.583904,303.37460,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 20:30:00,NaN,NaN,NaN,0.225049,0.410124,0.213138,56.343750,5.271484,28.531250,22.531250
2018-10-31 21:00:00,93495.180,17.786602,304.21630,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 21:30:00,NaN,NaN,NaN,0.279001,0.415198,0.265450,52.515625,5.472656,31.289062,15.753906
2018-10-31 22:00:00,93490.430,18.129929,305.69480,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 22:30:00,NaN,NaN,NaN,0.293909,0.404511,0.279648,58.140625,5.751953,31.187500,21.203125
2018-10-31 23:00:00,93461.890,18.254297,307.04504,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-10-31 23:30:00,NaN,NaN,NaN,0.271580,0.370735,0.257691,62.531250,5.417969,29.968750,27.156250

In [51]:
df.to_csv(output_file)